/**
 * transport/proto/generate.ts — GRPC-PG1 proto text emitter.
 *
 * Reads the Zod-anchored operation registry (`./registry.ts`) and emits a
 * deterministic `.proto` artifact. The emitted file defines:
 *
 *   - `syntax = "proto3";`
 *   - `package phalanx.hoplon.v1;`
 *   - Three transport-envelope messages (`HoplonEnvelope`, `HoplonStreamFrame`,
 *     `HoplonUnit`).
 *   - One `service HoplonService` with exactly one RPC per registry entry.
 *
 * Why an envelope instead of per-method reflected proto messages?
 *
 *   The Zod contracts in `src/hoplon/contracts/` are the single wire-level
 *   source of truth across HTTP (T1/T2) and MCP today; reflecting their full
 *   graph into idiomatic proto3 (discriminated unions, tuples, preprocessing,
 *   optional + nullable, literal-typed discriminants, recursive schemas)
 *   would either create a second schema source of truth or duplicate
 *   validation rules. PG1 deliberately declines that tradeoff: the wire
 *   payload inside `HoplonEnvelope.json_payload` is the Zod-validated DTO,
 *   and the proto surface only fixes the RPC method list, streaming
 *   posture, and transport metadata.
 *
 * Later PG/GRPC waves (SV1/CL1/ST1/EQ1) can decide whether structural
 * reflection is warranted. PG1 does not prejudge that.
 *
 * The function returns the proto file contents as a string; writing to disk
 * and verifying reproducibility is done from
 * `tests/transport/proto.generate.test.ts`.
 */

import {
  HOPLON_PROTO_OPERATIONS,
  type ProtoOperation,
} from './registry.js';

/** Stable, committed artifact path relative to the repo root. */
export const HOPLON_PROTO_ARTIFACT_PATH =
  'src/hoplon/transport/proto/generated/hoplon.proto';

/** Proto package identifier. Major-version bump ≡ wire-breaking change. */
export const HOPLON_PROTO_PACKAGE = 'phalanx.hoplon.v1';

/** Service name emitted in the proto file. */
export const HOPLON_PROTO_SERVICE = 'HoplonService';

/** Fixed header block — contains the regeneration instruction. */
const HEADER = `// Code generated by src/hoplon/transport/proto/generate.ts — DO NOT EDIT BY HAND.
//
// Source of truth: src/hoplon/contracts/ (Zod schemas).
// Regenerate with: HOPLON_PROTO_REGEN=1 npx vitest run tests/transport/proto.generate.test.ts
// Reproducibility check: npx vitest run tests/transport/proto.generate.test.ts
//
// PG1 (bounded opening move for t-024):
//   - Fixes the gRPC service surface and streaming posture per engine RPC.
//   - Wire payload is the Zod-validated JSON DTO inside HoplonEnvelope.json_payload.
//   - Does not add a runtime gRPC dependency; no server/client/streaming code yet.
//   - Does not create a second schema source of truth.
//
// Later waves (GRPC-SV1 / GRPC-CL1 / GRPC-ST1 / GRPC-EQ1) decide the runtime
// framework (@grpc/grpc-js vs nice-grpc), whether structural proto reflection
// replaces the envelope, and the cross-transport equivalence envelope. PG1
// intentionally keeps those decisions open.
`;

/**
 * Emit the `.proto` file contents for the current registry.
 *
 * The output is deterministic: same registry → byte-identical string.
 * The reproducibility test relies on this.
 */
export function generateHoplonProto(): string {
  const lines: string[] = [];

  lines.push(HEADER);
  lines.push('syntax = "proto3";');
  lines.push('');
  lines.push(`package ${HOPLON_PROTO_PACKAGE};`);
  lines.push('');

  // -- Envelope messages --------------------------------------------------
  lines.push('// Wire payload for every unary request and unary response.');
  lines.push('//');
  lines.push('// The Zod-validated JSON DTO for the operation is UTF-8 encoded into');
  lines.push('// json_payload. `schema_name` identifies which Zod schema the bytes must');
  lines.push('// roundtrip through (e.g. "CreateSnapshotRequestSchema"); servers and');
  lines.push('// clients look this up from the same registry that feeds this generator.');
  lines.push('message HoplonEnvelope {');
  lines.push('  bytes json_payload = 1;');
  lines.push('  string correlation_id = 2;');
  lines.push('  string schema_name = 3;');
  lines.push('  int32 schema_version = 4;');
  lines.push('}');
  lines.push('');

  lines.push('// Single server-stream frame. Used by server-streaming RPCs (e.g.');
  lines.push('// PackContext) where the response is delivered as a sequence of frames.');
  lines.push('// frame_kind distinguishes data / metadata / terminal frames and mirrors');
  lines.push('// the NDJSON frame kinds already used by the shipped HTTP streaming path.');
  lines.push('message HoplonStreamFrame {');
  lines.push('  bytes json_payload = 1;');
  lines.push('  string correlation_id = 2;');
  lines.push('  string frame_kind = 3;');
  lines.push('}');
  lines.push('');

  lines.push('// Body-less request marker for RPCs that take no request DTO today');
  lines.push('// (Health, Reconcile). correlation_id is carried explicitly so every');
  lines.push('// server-side op can be traced without inspecting gRPC metadata.');
  lines.push('message HoplonUnit {');
  lines.push('  string correlation_id = 1;');
  lines.push('}');
  lines.push('');

  // -- Service ------------------------------------------------------------
  lines.push(`service ${HOPLON_PROTO_SERVICE} {`);
  for (const op of HOPLON_PROTO_OPERATIONS) {
    const rpcLines = emitRpc(op);
    for (const rpcLine of rpcLines) {
      lines.push(rpcLine === '' ? '' : `  ${rpcLine}`);
    }
  }
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function emitRpc(op: ProtoOperation): readonly string[] {
  const requestMessage = op.hasRequestBody ? 'HoplonEnvelope' : 'HoplonUnit';
  const responseMessage =
    op.streaming === 'server' ? 'stream HoplonStreamFrame' : 'HoplonEnvelope';

  const comment = `// ${op.method} — ${op.docLine}`;
  const rpc = `rpc ${op.rpcName}(${requestMessage}) returns (${responseMessage});`;
  return [comment, rpc, ''];
}
