import {
  AuditRequestSchema,
  AuditResultSchema,
  CompressedRetryContextSchema,
  CompressRetryContextRequestBodySchema,
  ComputeMinimalPatchRequestSchema,
  CreateSnapshotRequestSchema,
  DescribeProjectRequestSchema,
  DescribeProjectResultSchema,
  DryRunRequestSchema,
  ExtractRollbackTemplateRequestSchema,
  ExtractStructuralTemplateRequestSchema,
  GetRelevantTestsRequestSchema,
  MinimalPatchSchema,
  PackedContextSchema,
  PackContextRequestSchema,
  PreflightRequestSchema,
  PreflightResultSchema,
  QueryStructureRequestSchema,
  QueryStructureResultSchema,
  RevertRequestSchema,
  RevertResultSchema,
  RollbackTemplateSchema,
  SearchSymbolsRequestSchema,
  SearchSymbolsResultSchema,
  SnapshotResultSchema,
  StructuralTemplateSchema,
  TestOracleResultSchema,
} from './schemaRefs.js';
import type { ProtoOperation } from './registryTypes.js';

export const CORE_PROTO_OPERATIONS: readonly ProtoOperation[] = [
  {
    method: 'createSnapshot', rpcName: 'CreateSnapshot', hasRequestBody: true,
    streaming: 'none', requestSchema: CreateSnapshotRequestSchema,
    responseSchema: SnapshotResultSchema,
    docLine: 'Capture a contracted writable scope as a snapshot.',
  },
  {
    method: 'auditDiff', rpcName: 'AuditDiff', hasRequestBody: true,
    streaming: 'none', requestSchema: AuditRequestSchema,
    responseSchema: AuditResultSchema,
    docLine: 'Compare current tree against the contracted manifest.',
  },
  {
    method: 'revertUncontracted', rpcName: 'RevertUncontracted', hasRequestBody: true,
    streaming: 'none', requestSchema: RevertRequestSchema,
    responseSchema: RevertResultSchema,
    docLine: 'Restore contracted files to their snapshotted state.',
  },
  {
    method: 'packContext', rpcName: 'PackContext', hasRequestBody: true,
    streaming: 'server', requestSchema: PackContextRequestSchema,
    responseSchema: PackedContextSchema,
    docLine: 'Return AST-bounded context slices (server-streamed).',
  },
  {
    method: 'dryRun', rpcName: 'DryRun', hasRequestBody: true,
    streaming: 'none', requestSchema: DryRunRequestSchema,
    responseSchema: AuditResultSchema,
    docLine: 'Evaluate proposed changes without touching disk.',
  },
  {
    method: 'preflight', rpcName: 'Preflight', hasRequestBody: true,
    streaming: 'none', requestSchema: PreflightRequestSchema,
    responseSchema: PreflightResultSchema,
    docLine: 'Run Stage 1 pre-execution gates against the manifest.',
  },
  {
    method: 'queryStructure', rpcName: 'QueryStructure', hasRequestBody: true,
    streaming: 'none', requestSchema: QueryStructureRequestSchema,
    responseSchema: QueryStructureResultSchema,
    docLine: 'Execute tree-sitter S-expression queries over files.',
  },
  {
    method: 'extractStructuralTemplate', rpcName: 'ExtractStructuralTemplate',
    hasRequestBody: true, streaming: 'none',
    requestSchema: ExtractStructuralTemplateRequestSchema,
    responseSchema: StructuralTemplateSchema,
    docLine: 'Extract a deterministic structural skeleton for LLM context.',
  },
  {
    method: 'extractRollbackTemplate', rpcName: 'ExtractRollbackTemplate',
    hasRequestBody: true, streaming: 'none',
    requestSchema: ExtractRollbackTemplateRequestSchema,
    responseSchema: RollbackTemplateSchema,
    docLine: 'Emit per-file rollback skeletons from a committed snapshot.',
  },
  {
    method: 'computeMinimalPatch', rpcName: 'ComputeMinimalPatch',
    hasRequestBody: true, streaming: 'none',
    requestSchema: ComputeMinimalPatchRequestSchema,
    responseSchema: MinimalPatchSchema,
    docLine: 'Compute a minimal patch from a BLOCK AuditResult (sync engine op).',
  },
  {
    method: 'compressRetryContext', rpcName: 'CompressRetryContext',
    hasRequestBody: true, streaming: 'none',
    requestSchema: CompressRetryContextRequestBodySchema,
    responseSchema: CompressedRetryContextSchema,
    docLine: 'Compress retry attempts into a structural delta (sync engine op).',
  },
  {
    method: 'getRelevantTests', rpcName: 'GetRelevantTests', hasRequestBody: true,
    streaming: 'none', requestSchema: GetRelevantTestsRequestSchema,
    responseSchema: TestOracleResultSchema,
    docLine: 'Determine which test files import the given modified files.',
  },
  {
    method: 'searchSymbols', rpcName: 'SearchSymbols', hasRequestBody: true,
    streaming: 'none', requestSchema: SearchSymbolsRequestSchema,
    responseSchema: SearchSymbolsResultSchema,
    docLine: 'Local AST-aware structural search across the project.',
  },
  {
    method: 'describeProject', rpcName: 'DescribeProject', hasRequestBody: true,
    streaming: 'none', requestSchema: DescribeProjectRequestSchema,
    responseSchema: DescribeProjectResultSchema,
    docLine: 'Local AST-aware project orientation summary.',
  },
];
