import {
  AnalyzeBlastRadiusRequestSchema,
  AnalyzeBlastRadiusResultSchema,
  AnomalyScoreSchema,
  DescribeCapabilitiesRequestSchema,
  DescribeCapabilitiesResultSchema,
  EngineHealthSchema,
  EphemeralStructuralSandboxRequestSchema,
  EphemeralStructuralSandboxResultSchema,
  FindReferencingSymbolsRequestSchema,
  FindReferencingSymbolsResultSchema,
  GcRequestSchema,
  GcResultSchema,
  IndexSemanticCorpusRequestSchema,
  IndexSemanticCorpusResultSchema,
  PredictViolationRiskRequestSchema,
  ReconcileReportSchema,
  ScoreAnomalyRequestSchema,
  SeeCodebaseEnvelopeSchema,
  SeeCodebaseRequestSchema,
  SemanticOverlayClearRequestSchema,
  SemanticOverlayClearResultSchema,
  SemanticOverlayRefreshRequestSchema,
  SemanticOverlayRefreshResultSchema,
  SemanticSearchRequestSchema,
  SemanticSearchResultSchema,
  SynthesizeInterfaceStubsRequestSchema,
  SynthesizeInterfaceStubsResultSchema,
  ViolationPredictionSchema,
} from './schemaRefs.js';
import type { ProtoOperation } from './registryTypes.js';

export const EXTENDED_PROTO_OPERATIONS: readonly ProtoOperation[] = [
  {
    method: 'seeCodebase', rpcName: 'SeeCodebase', hasRequestBody: true,
    streaming: 'none', requestSchema: SeeCodebaseRequestSchema,
    responseSchema: SeeCodebaseEnvelopeSchema,
    docLine: 'Unified agent-facing read/search macro over structural + raw primitives (t-062).',
  },
  {
    method: 'predictViolationRisk', rpcName: 'PredictViolationRisk',
    hasRequestBody: true, streaming: 'none',
    requestSchema: PredictViolationRiskRequestSchema,
    responseSchema: ViolationPredictionSchema,
    docLine: 'Advisory violation-risk predictor (never affects PASS/BLOCK).',
  },
  {
    method: 'scoreAnomaly', rpcName: 'ScoreAnomaly', hasRequestBody: true,
    streaming: 'none', requestSchema: ScoreAnomalyRequestSchema,
    responseSchema: AnomalyScoreSchema,
    docLine: 'Advisory anomaly score over audit log history.',
  },
  {
    method: 'analyzeBlastRadius', rpcName: 'AnalyzeBlastRadius',
    hasRequestBody: true, streaming: 'none',
    requestSchema: AnalyzeBlastRadiusRequestSchema,
    responseSchema: AnalyzeBlastRadiusResultSchema,
    docLine: 'Advisory blast-radius consumer over findReferences.',
  },
  {
    method: 'findReferencingSymbols', rpcName: 'FindReferencingSymbols',
    hasRequestBody: true, streaming: 'none',
    requestSchema: FindReferencingSymbolsRequestSchema,
    responseSchema: FindReferencingSymbolsResultSchema,
    docLine: 'Advisory referencing-symbol lookup over findReferences.',
  },
  {
    method: 'synthesizeInterfaceStubs', rpcName: 'SynthesizeInterfaceStubs',
    hasRequestBody: true, streaming: 'none',
    requestSchema: SynthesizeInterfaceStubsRequestSchema,
    responseSchema: SynthesizeInterfaceStubsResultSchema,
    docLine: 'Deterministic interface-stub synthesis (advisory).',
  },
  {
    method: 'ephemeralStructuralSandbox', rpcName: 'EphemeralStructuralSandbox',
    hasRequestBody: true, streaming: 'none',
    requestSchema: EphemeralStructuralSandboxRequestSchema,
    responseSchema: EphemeralStructuralSandboxResultSchema,
    docLine: 'Read-only in-memory structural sandbox for synthetic snippets.',
  },
  {
    method: 'describeCapabilities', rpcName: 'DescribeCapabilities',
    hasRequestBody: true, streaming: 'none',
    requestSchema: DescribeCapabilitiesRequestSchema,
    responseSchema: DescribeCapabilitiesResultSchema,
    docLine: 'Typed extension-capability catalog for the current engine.',
  },
  {
    method: 'indexSemanticCorpus', rpcName: 'IndexSemanticCorpus',
    hasRequestBody: true, streaming: 'none',
    requestSchema: IndexSemanticCorpusRequestSchema,
    responseSchema: IndexSemanticCorpusResultSchema,
    docLine: 'Index caller-supplied semantic corpus documents under a project.',
  },
  {
    method: 'semanticSearch', rpcName: 'SemanticSearch', hasRequestBody: true,
    streaming: 'none', requestSchema: SemanticSearchRequestSchema,
    responseSchema: SemanticSearchResultSchema,
    docLine: 'Run advisory semantic retrieval over the indexed project corpus.',
  },
  {
    method: 'refreshSemanticOverlay', rpcName: 'RefreshSemanticOverlay',
    hasRequestBody: true, streaming: 'none',
    requestSchema: SemanticOverlayRefreshRequestSchema,
    responseSchema: SemanticOverlayRefreshResultSchema,
    docLine: 'Refresh advisory live-session semantic overlay rows.',
  },
  {
    method: 'clearSemanticOverlay', rpcName: 'ClearSemanticOverlay',
    hasRequestBody: true, streaming: 'none',
    requestSchema: SemanticOverlayClearRequestSchema,
    responseSchema: SemanticOverlayClearResultSchema,
    docLine: 'Clear advisory live-session semantic overlay rows.',
  },
  {
    method: 'health', rpcName: 'Health', hasRequestBody: false,
    streaming: 'none', requestSchema: null,
    responseSchema: EngineHealthSchema,
    docLine: 'Engine + adapter health probe (no request body).',
  },
  {
    method: 'gc', rpcName: 'Gc', hasRequestBody: true,
    streaming: 'none', requestSchema: GcRequestSchema,
    responseSchema: GcResultSchema,
    docLine: 'Delete snapshot records by filter (right-to-erasure / TTL).',
  },
  {
    method: 'reconcile', rpcName: 'Reconcile', hasRequestBody: false,
    streaming: 'none', requestSchema: null,
    responseSchema: ReconcileReportSchema,
    docLine: 'Reconcile orphaned snapshot records against the object store.',
  },
];
